version: '2'
services:
  dovecot:
    image: wailram/dovecot:latest
    environment:
      SMTP_SERVER: ${IP}
      SERVER_HOSTNAME: ${DOMAIN_NAME}
      DESTINATION: ${DESTINATION}
      USERNAME_ACCOUNT: ${USERNAME_ACCOUNT}
      PASSWORD_ACCOUNT: ${PASSWORD_ACCOUNT}
    expose:
    - "143"
    - "993"
    env_file:
    - .env
    restart: always
